---
date: <% tp.date.now("YYYY-MM-DD") %>
tags:
  - typescript
  - express
  - 設計
  - オブジェクト指向
  - DI
  - 3層アーキテクチャ
  - デザインパターン
aliases:
  - <% tp.file.title %>
---

## パッケージのインストール

```bash
npm i express-async-errors
```

## ソースを変更

```ts
// src/main.ts

import express from 'express';
import morgan from 'morgan';
import 'express-async-errors'; // 追加

const PORT = 3000;

const app = express();

app.use(morgan('dev'));

app.get('/api/hello', async (req, res) => {
  res.json({
    message: 'Hello Express !!!',
  });
});

// あえて例外を発生させるエンドポイントを作成
app.get('/api/error', async (req, res) => {
  throw new Error('Error endpoint');
});

// エラーハンドリング
const errorHandler = (
  err: any,
  _req: express.Request,
  res: express.Response,
  _next: express.NextFunction
) => {
  console.error('Unexpected error occurred', err);

  // ステータスコード500でjsonを送信
  res.status(500).send({
    message: 'Unexpected error occurred',
  });
};

// 追加
app.use(errorHandler);

app.listen(PORT, () => {
  console.log(`Reversi application started: http://localhost:${PORT}`);
});
```

これで例外をキャッチしたものはすべてエラーハンドリング用の関数が呼ばれて 500 エラーが送信される。
